CREATE TABLE CITY (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR, STATE VARCHAR, COUNTRY VARCHAR);

INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('SAN FRANCISCO', 'CA', 'US');

CREATE TABLE Person (ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR, CITY VARCHAR, COUNTRY VARCHAR);

INSERT INTO Person (NAME, CITY, COUNTRY) VALUES ('lky', 'SZ', 'CN');

